### ISSUE TITLE
UnPickling Error

### ISSUE THREAD

**Issue by jmchumbo** [tengyu-liu/GenDexGrasp#8]
Hello,

Whenever I download all the files and attempt to train the CMap-CVAE model using train_cvae.py, I encounter an error as depicted in the attached files. The error message is: "pickle.UnpicklingError: invalid load key, '<'."

Furthermore, I'm experiencing the same problem when running "python vis_multidex.py". I have attempted to download the files multiple times on different computers, but the errors persist.

Do you have any insights into what might be causing this issue?

Thank you in advance.
João Chumbinho
![GenDexGrasp Errors](https://github.com/tengyu-liu/GenDexGrasp/assets/38738356/ca9be65e-2cfd-45ea-b370-050e389055d3)

**Comment by Xiaoyao-Li** [comment]
Hi @jmchumbo , thanks for your interest in our work.

However, I have not meet this problem before. Could you please check if `MultiDex/shadowhand/shadowhand.pt` MD5 code is `ffbe59d36e7a7c0486075c1bb5ca4fc9`. Run `md5sum MultiDex/shadowhand/shadowhand.pt` in your project folder.

Noticed that you use Python 3.7 in your environment, it could potentially lead to a torch version mismatch with default environment setup. This might cause issues when using `torch.load()`.

After using Torch to store data for a while, I realized that it is not standard and convenient. If necessary, I will consider switching to use pickle for data storage.

Hope can help you,
Puhao.
